import type { PageReport, Report, Severity } from "../types.js";

const ICON: Record<Severity, string> = { error: "🔴", warning: "🟡", info: "🔵" };

/** Render a report as a shareable Markdown document. */
export function toMarkdown(report: Report): string {
  const lines: string[] = [];
  const s = report.summary;
  lines.push("# a11ylint report", "");
  lines.push(
    `**Overall: ${s.score}/100 (${s.grade})** · ${s.pages} page(s) · ` +
      `${s.errors} error(s), ${s.warnings} warning(s), ${s.infos} info`,
    "",
  );
  lines.push(`> Generated by ${report.tool} v${report.version} on ${report.generatedAt}`, "");

  for (const p of report.pages) lines.push(...pageSection(p));
  return lines.join("\n");
}

function pageSection(p: PageReport): string[] {
  const lines: string[] = [];
  const title = p.title ? ` — ${p.title}` : "";
  lines.push(`## ${p.source}${title}`, "");
  lines.push(`**Score: ${p.score}/100 (${p.grade})**`, "");

  if (p.categories.length > 0) {
    lines.push("| Category | Score | 🔴 | 🟡 | 🔵 |");
    lines.push("| --- | --- | --- | --- | --- |");
    for (const c of p.categories) {
      lines.push(`| ${c.label} | ${c.score} | ${c.error} | ${c.warning} | ${c.info} |`);
    }
    lines.push("");
  }

  if (p.issues.length === 0) {
    lines.push("✅ No accessibility issues found.", "");
    return lines;
  }

  lines.push("### Issues", "");
  for (const i of p.issues) {
    const loc = i.line ? ` _(line ${i.line})_` : "";
    const wcag = i.wcag ? ` — WCAG ${i.wcag.criterion} (${i.wcag.level})` : "";
    lines.push(`- ${ICON[i.severity]} **${i.message}**${loc}${wcag}`);
    if (i.snippet) lines.push(`  - \`${i.snippet.replace(/`/g, "'")}\``);
    if (i.detail) lines.push(`  - ${i.detail}`);
    if (i.fix) lines.push(`  - 💡 ${i.fix}`);
  }
  lines.push("");
  return lines;
}
